services:
  dashboard-searchsport:
    build: .
    container_name: searchsport_dashboard
    command: >
      streamlit run dashboard.py
      --server.address=0.0.0.0
      --server.port=8501
      --server.headless=true
      --server.fileWatcherType=none
      --browser.gatherUsageStats=false
    ports:
      - "8501:8501"
    depends_on:
      - api-searchsport

  api-searchsport:
    build: .
    container_name: searchsport_api
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"